AllCops:
  NewCops: enable
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Security/MarshalLoad:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Style/ClassVars:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false